- name: variable in yaml
  hosts: mongodb
  tasks:
  - name: print the first value
    ansible.builtin.debug:
     message: "The first value is: "
  - name: print the second value
    ansible.builtin.debug:
      message: "The secong value is: "