- name: install and run nginx
  hosts: mongodb
  tasks:
  - name: inatall nginx
    ansible.builtin.yum:
      name: nginx
      state: installed
  - name: run nginx
    ansible.builtin.service:
      name: nginx
      state: restarted