- name: retriving variables from onther files
  hosts: localhost
  vars_files:
    -variable.yaml
  tasks:
    - name: printing the variables from other files
      ansible.builtin.debug:
        msg: "Hi {{NAME}}, Your age is : {{AGE}} and your gender is: {{GENDER}}"