- name: Entering the variables from prompt
  hosts: localhost
  vars_prompt:
  - name: USERNAME
    prompt: Please enter user name
    private: false
  - name: PASSWORD
    prompt: Please enter password
    private: true
  tasks: getting the values from prompt line
  - name: Printing the prompt values
    ansible.builtin.debug:
    msg: "The username is : {{USERNAME} ans password is: {{PASSWORD}}}"