- name: check the roboshop-user exist or not
  hosts: mongodb
  tasks:
  - name: check user id
    ansible.builtin.command: id roboshop
    register: output
    ignore_errors: true
  - name: print userID
    ansible.builtin.debug:
      msg: "The roboshop userID: {{output}}"
  