- name: check the roboshop-user exist or not
  hosts: localhost
  tasks:
  - name: check user id
    ansible.builtin.command: id roboshop
    register: output
  - name: printing the output value
    ansible.builtin.debug:
      msg: "The roboshop userID: {{output}}"
  