- name: Entering the variables from prompt
  hosts: localhost
  vars_prompt:
  - name: USERNAME
    prompt: Please enter user name
    private: false
  - name: PASSWORD
    prompt: Please enter password
    private: true
  tasks:
  - name: Printing the prompt values
    ansible.builtin.debug:
      msg: "The Username: {{USERNAME}}, Password: {{PASSWORD}}"
    when: '{{PASSWORD}}' == "Venkat@1095"