- name: installing packages
  hosts: localhost
  become: yes
  tasks:
  - name: install packege
    ansible.builtin.yum:
      name: "{{item}}"
      state: installed
  - name: print the status
    ansible.builtin.debug:
      msg: "Installatin..Success.."
    loop:
    - nginx
    - postfix
    - mysql