- name: installing packages
  hosts: localhost
  become: yes
  tasks:
  - name: install packege
    ansible.builtin.yum:
      name: "{{item.name}}"
      state: "{{item.state}}"
    loop:
    - {name: 'nginx', state: 'installed'}
    - {name: 'postfix', state: 'absent'}
    - {name: 'mysql', state: 'installed'}