- name: install catalogue component
  hosts: catalogue
  become: yes
  tasks:
  - name: install NPM
    ansible.builtin.shell: "curl -sL https://rpm.nodesource.com/setup_lts.x | bash"

  - name: install nodejs
    ansible.builtin.yum:
      name: nodejs
      state: installed
  
  - name: check user roboshop
    ansible.builtin.command: id roboshop
    register: output
    ignore_errors: yes