- name: install catalogue component
  hosts: catalogue
  become: yes
  tasks:
  - name: install NPM
    ansible.builtin.shell: "curl -sL https://rpm.nodesource.com/setup_lts.x | bash"

  - name: install nodejs
    ansible.builtin.yum:
      name: nodejs
      state: installed
  
  - name: check user roboshop exist or not
    ansible.builtin.command: id roboshop
    register: output
    ignore_errors: yes

  - when: output.rc != 0
    name: add user name called rooboshop
    ansible.builtin.user:
      name: roboshop

  - name: check /app directory is exists ir not
    ansible.builtin.stat:
      path: /app
    register: directory

  - name: print the output of stat
    andible.builtin.debug:
      msg: "output: {{directory}}"
    