- name: install mysql component
  hosts: mysql
  become: yes
  tasks:
  - name: modules disable
    ansible.builtin.command: yum module disable mysql -y 

  - name: copy the mysql repo
    ansible.builtin.copy:
      src: mysql.repo
      dest: /etc/yum.repos.d/mysql.repo

  - name: install mysql-community-server
    ansible.builtin.yum:
      name: mysql-community-server -y
      state: installed

  - name: enable and restart
    ansible.builtin.service:
      name: mysqld
      enabled: true
      state: restarted
  
  - name: set root password
    ansible.builtin.command: mysql_secure_installation --set-root-pass RoboShop@1