- name: install rabbitmq component
  hosts: rabbitmq
  become: yes
  tasks:
  - name: Configure YUM Repos from the script
    ansible.builtin.shell: "curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | bash"

  - name: Configure YUM Repos for RabbitMQ.
    ansible.builtin.shell: "curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | bash"

  - name: install rabbitmq-server
    ansible.builtin.yum:
      name: rabbitmq-server
      state: installed

  - name: enable and restart rabbitmq-server
    ansible.builtin.service:
      name: rabbitmq-server
      state: restarted
      enabled: yes
  
  - name: created user roboshop
    ansible.builtin.shell: rabbitmqctl add_user roboshop roboshop123

  - name: setup user roboshop permissions
    ansible.builtin.shell: 'rabbitmqctl set_permissions -p / roboshop ".*" ".*" ".*" '