- name: install user component
  hosts: user
  become: yes
  tasks:
  - name: install NPM
    ansible.builtin.shell: "curl -sL https://rpm.nodesource.com/setup_lts.x | bash"

  - name: install nodejs
    ansible.builtin.yum:
      name: nodejs
      state: installed
  
  - name: check user roboshop exist or not
    ansible.builtin.command: id roboshop
    register: output
    ignore_errors: yes

  - when: output.rc != 0
    name: add user name called rooboshop
    ansible.builtin.user:
      name: roboshop

  - name: check /app directory is exists ir not
    ansible.builtin.stat:
      path: /app
    register: directory
    ignore_errors: yes

  - name: print the output of stat
    ansible.builtin.debug:
      msg: "output: {{directory}}"
  
  - when: directory.stat.exists == False
    name: create /app directory
    ansible.builtin.file:
      path: /app
      state: directory
  
  - name: install user artifact
    ansible.builtin.get_url:
      url: https://roboshop-builds.s3.amazonaws.com/user.zip
      dest: /tmp
  
  - name: Unarchive a file that is already on the remote machine i.e zipfile
    ansible.builtin.unarchive:
      src: /tmp/user.zip
      dest: /app
      remote_src: yes

  - name: install npm dependencies
    ansible.builtin.command: npm install
    args:
      chdir: /app

  - name: copy the user conf
    ansible.builtin.copy:
      src: user.service
      dest: /etc/systemd/system/user.service

  - name: Reload service httpd, in all cases
    ansible.builtin.systemd:
      name: user
      daemon-reload: true

  - name: Restart user
    ansible.builtin.service:
      name: user
      enabled: true
      state: started
  
  - name: copy mongo.repo
    ansible.builtin.copy:
      src: mongo.repo
      dest: /etc/yum.repos.d/mongo.repo
      
  - name: install mongodb
    ansible.builtin.yum:
      name: mongodb-org-shell
      state: installed

  - name: host mongodb
    ansible.builtin.command: mongo --host mongodb.venkateshamsonnalia143.online < /app/schema/user.js

    
    